---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2929125715-SxkyFgvE0RCHko79x7eHPedEAYng6kImSXo5Hrj
:access_token_secret: xTa1ZPXdkGDsw9y6JcwwS4hl96jv2ZLOyewrVLfQ2L7P0
